name: multiple-daily-cron
on:
  schedule:
    - cron: "1 0 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Refresh Top Feeds everyday
        run: |
          curl --request GET \
          --url 'https://rss-swift.vercel.app/api/top_feeds/triggered'
